# Generated by Django 4.1 on 2022-09-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baas_objects", "0002_rename_document_object_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objectclass",
            name="max_object_size",
        ),
        migrations.RemoveField(
            model_name="objectclass",
            name="max_per_user",
        ),
        migrations.AddField(
            model_name="objectclass",
            name="allow_anonymous",
            field=models.BooleanField(default=True),
        ),
    ]
